
//You are given two strings s and t.

//String t is generated by random shuffling string s and then add one more letter at a random position.

//Return the letter that was added to t.


char findTheDifference(char* s, char* t) {
	int i, s_ = 0, t_ = 0;
	
    i = 0;
	while(s[i] != '\0'){
		s_ += s[i] - 'A';
		i++;
	}

    i = 0;
	while(t[i] != '\0'){
		t_ += t[i] - 'A';
		i++;
	}
	
	return t_ - s_ + 'A';
}


